plugin 'cocoapods-user-defined-build-types'

enable_user_defined_build_types!

platform :ios, '12.0'
#use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :build_type => :dynamic_framework, :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :build_type => :dynamic_framework, :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :build_type => :dynamic_framework, :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :build_type => :dynamic_framework, :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :build_type => :dynamic_framework, :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :build_type => :dynamic_framework, :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'TensorFlowLiteSwift', :build_type => :static_framework
  pod 'TensorFlowLiteTaskText', :build_type => :dynamic_framework
  pod 'GoogleMLKit/TextRecognition', :build_type => :dynamic_framework
  pod 'GoogleMLKit/FaceDetection', :build_type => :dynamic_framework
  pod 'GoogleMLKit/ImageLabeling', :build_type => :dynamic_framework
  pod 'ZXingObjC', :build_type => :dynamic_framework
  pod 'GZIP', :build_type => :dynamic_framework
  pod 'SSZipArchive', :build_type => :dynamic_framework

end
